//viewed images types
export const GET_VIEWED_IMAGES_STARTED = 'GET_VIEWED_IMAGES_STARTED';
export const GET_VIEWED_IMAGES_SUCCEDED = 'GET_VIEWED_IMAGES_SUCCEDED';
export const GET_VIEWED_IMAGES_FAILED = 'GET_VIEWED_IMAGES_FAILED';
export const SET_VIEWED_IMAGES_STARTED = 'SET_VIEWED_IMAGES_STARTED';
export const SET_VIEWED_IMAGES_SUCCEDED = 'SET_VIEWED_IMAGES_SUCCEDED';
export const SET_VIEWED_IMAGES_FAILED = 'SET_VIEWED_IMAGES_FAILED';
export const DELETE_VIEWED_IMAGES_STARTED = 'DELETE_VIEWED_IMAGES_STARTED';
export const DELETE_VIEWED_IMAGES_SUCCEDED = 'DELETE_VIEWED_IMAGES_SUCCEDED';
export const DELETE_VIEWED_IMAGES_FAILED = 'DELETE_VIEWED_IMAGES_FAILED';
